name: ele882-assignment3
channels:
    - default
    - conda-forge
dependencies:
    - python=3.8
    - numpy=1.19
    - pip
    - scikit-image=0.17
    - pip:
        - flake8
        - import-linter~=1.2
        - pytest
